In [9]:
import pandas as pd
football = pd.read_csv('D:\Data Scientist_Skill Factory/data_sf.csv')
football.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12897 entries, 0 to 12896
Data columns (total 42 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       12897 non-null  int64
 1   Name             12897 non-null  object
 2   Age              12897 non-null  int64
 3   Nationality      12897 non-null  object
 4   Club             12897 non-null  object
 5   Value            12897 non-null  int64
 6   Wage             12897 non-null  int64
 7   Position         12897 non-null  object
 8   Crossing         12897 non-null  int64
 9   Finishing        12897 non-null  int64
 10  HeadingAccuracy  12897 non-null  int64
 11  ShortPassing     12897 non-null  int64
 12  Volleys          12897 non-null  int64
 13  Dribbling        12897 non-null  int64
 14  Curve            12897 non-null  int64
 15  FKAccuracy       12897 non-null  int64
 16  LongPassing      12897 non-null  int64
 17  BallControl      12897 non-null  int64
 18  Acceleration     12897 non-null  int64
 19  SprintSpeed      12897 non-null  int64
 20  Agility          12897 non-null  int64
 21  Reactions        12897 non-null  int64
 22  Balance          12897 non-null  int64
 23  ShotPower        12897 non-null  int64
 24  Jumping          12897 non-null  int64
 25  Stamina          12897 non-null  int64
 26  Strength         12897 non-null  int64
 27  LongShots        12897 non-null  int64
 28  Aggression       12897 non-null  int64
 29  Interceptions    12897 non-null  int64
 30  Positioning      12897 non-null  int64
 31  Vision           12897 non-null  int64
 32  Penalties        12897 non-null  int64
 33  Composure        12897 non-null  int64
 34  Marking          12897 non-null  int64
 35  StandingTackle   12897 non-null  int64
 36  SlidingTackle    12897 non-null  int64
 37  GKDiving         12897 non-null  int64
 38  GKHandling       12897 non-null  int64
 39  GKKicking        12897 non-null  int64
 40  GKPositioning    12897 non-null  int64
 41  GKReflexes       12897 non-null  int64
dtypes: int64(38), object(4)
memory usage: 4.1+ MB

In [15]:
import pandas as pd
football = pd.read_csv('D:\Data Scientist_Skill Factory/data_sf.csv')
football.Value.min()

0

# 5.8 Задание 1. Какова средняя скорость (SprintSpeed) футболистов, зарплата (Wage) которых выше среднего? Ответ округлите до сотых.

In [66]:
import pandas as pd
football = pd.read_csv('D:\Data Scientist_Skill Factory/data_sf.csv')
football[football.Wage > football.Wage.mean()].SprintSpeed.mean()

67.56638061585058

# 5.8 Задание 2. Какова средняя скорость (SprintSpeed) футболистов, зарплата (Wage) которых ниже среднего? Ответ округлите до сотых.

In [67]:
import pandas as pd
football = pd.read_csv('D:\Data Scientist_Skill Factory/data_sf.csv')
football[football.Wage < football.Wage.mean()].SprintSpeed.mean()

62.41425430560645

# 5.8 Задание 3. Какую позицию (Position) занимает футболист с самой высокой зарплатой (Wage)?

In [71]:
import pandas as pd
football = pd.read_csv('D:\Data Scientist_Skill Factory/data_sf.csv')
football[football.Wage == football.Wage.max()].Position

0    RF
Name: Position, dtype: object

# 5.8 Задание 4. Сколько пенальти (Penalties) забили бразильские (Nationality, Brazil) футболисты за период, данные о котором представлены в датасете?

In [72]:
import pandas as pd
football = pd.read_csv('D:\Data Scientist_Skill Factory/data_sf.csv')
football[football.Nationality == 'Brazil'].Penalties.sum()

22789

# 5.8 Задание 5. Укажите средний возраст (Age) игроков, у которых точность удара головой (HeadingAccuracy) > 50. Ответ округлите до сотых.

In [73]:
import pandas as pd
football = pd.read_csv('D:\Data Scientist_Skill Factory/data_sf.csv')
football[football.HeadingAccuracy >50].Age.mean()

25.58771113179944

# 5.8 Задание 6. Укажите возраст (Age) самого молодого игрока, у которого хладнокровие (Composure) и реакция (Reactions) превышают 90% от максимального значения, представленного в датасете.

In [74]:
import pandas as pd
football = pd.read_csv('D:\Data Scientist_Skill Factory/data_sf.csv')
football[(football.Composure > 0.9*football.Composure.max())&(football.Reactions > 0.9*football.Reactions.max())].Age.min()

24

# 5.8 Задание 7. Определите, на сколько средняя реакция (Reactions) самых взрослых игроков (т.е. игроков, чей возраст (Age) равен максимальному) больше средней реакции самых молодых игроков. Ответ округлите до сотых.

In [76]:
import pandas as pd
football = pd.read_csv('D:\Data Scientist_Skill Factory/data_sf.csv')
football[football.Age == football.Age.max()].Reactions.mean()-football[football.Age == football.Age.min()].Reactions.mean()

22.642857142857146

# 5.8 Задание 8. Из какой страны (Nationality) происходит больше всего игроков, чья стоимость (Value) превышает среднее значение?

In [60]:
import pandas as pd
football = pd.read_csv('D:\Data Scientist_Skill Factory/data_sf.csv')
football[(football.Value > football.Value.mean())].Nationality.describe(include = ['top'])

count      1747
unique       98
top       Spain
freq        211
Name: Nationality, dtype: object

# 5.8 Задание 9. Определите, во сколько раз средняя зарплата (Wage) голкипера (Position, GK) с максимальным значением показателя " Рефлексы" (GKReflexes) выше средней зарплаты голкипера с максимальным значением показателя "Владение мячом" (GKHandling). Ответ округлите до сотых.

In [62]:
import pandas as pd
football = pd.read_csv('D:\Data Scientist_Skill Factory/data_sf.csv')
football[(football.Position == 'GK')&(football.GKReflexes == football.GKReflexes.max())].Wage.mean()/football[(football.Position == 'GK')&(football.GKHandling == football.GKHandling.max())].Wage.mean()

2.765957446808511

# 5.8 Задание 10. Определите, во сколько раз средняя сила удара (ShotPower) самых агрессивных игроков (игроков с максимальным значением показателя "Агрессивность" (Aggression)) выше средней силы удара игроков с минимальной агрессией. Ответ округлите до сотых.

In [65]:
import pandas as pd
football = pd.read_csv('D:\Data Scientist_Skill Factory/data_sf.csv')
football[(football.Aggression == football.Aggression.max())].ShotPower.mean()/football[(football.Aggression == football.Aggression.min())].ShotPower.mean()

2.076923076923077

# 6.3 Задание 1. Сколько футбольных клубов представлено в датасете?

In [4]:
import pandas as pd
football = pd.read_csv('D:\Data Scientist_Skill Factory/data_sf.csv')
s = football['Club'].value_counts()
len(s.index)

650

# 6.3 Задание 2. Отметьте названия футбольных клубов, представленных в датасете наибольшим количеством игроков.

In [6]:
import pandas as pd
football = pd.read_csv('D:\Data Scientist_Skill Factory/data_sf.csv')
s = football['Club'].value_counts()
display(s)

V-Varen Nagasaki     30
Shonan Bellmare      30
De Graafschap        29
Padova               29
FC Emmen             29
                     ..
Dijon FCO             8
Vitória Guimarães     7
Dinamo Zagreb         7
GD Chaves             7
Atlético Mineiro      6
Name: Club, Length: 650, dtype: int64

# 6.4 Задание 1. Данные об игроках каких позиций (Position) занимают более 10% датасета?

In [7]:
import pandas as pd
football = pd.read_csv('D:\Data Scientist_Skill Factory/data_sf.csv')
s = football['Position'].value_counts(normalize=True)
display(s)

GK     0.127239
ST     0.117237
CB     0.108785
CM     0.082732
LB     0.077692
RB     0.073505
RM     0.059394
LM     0.056447
CDM    0.053578
CAM    0.049081
RCB    0.032411
LCB    0.031713
LW     0.018764
RCM    0.018609
RW     0.018376
LCM    0.018066
LDM    0.011476
RDM    0.010700
LS     0.009382
RS     0.008839
RWB    0.005428
LWB    0.004652
CF     0.003954
LF     0.000620
RF     0.000465
LAM    0.000465
RAM    0.000388
Name: Position, dtype: float64

# 6.4 Задание 3. В каких пределах находятся худшие 20% показателей точности ударов ногой (FKAccuracy)?

In [8]:
import pandas as pd
football = pd.read_csv('D:\Data Scientist_Skill Factory/data_sf.csv')
s = football['FKAccuracy'].value_counts(bins=5)
display(s)

(21.2, 39.4]     4859
(39.4, 57.6]     3957
(57.6, 75.8]     2108
(2.908, 21.2]    1760
(75.8, 94.0]      213
Name: FKAccuracy, dtype: int64

# 6.6 Задание 1. У какого процента испанских футболистов (Nationality = 'Spain') зарплата (Wage) находится в пределах 25% минимума от наблюдаемого уровня зарплат среди испанских игроков? Ответ дайте в виде целого числа (округлите полученный результат) без знака %.

In [52]:
import pandas as pd
football = pd.read_csv('D:\Data Scientist_Skill Factory/data_sf.csv')
Total_number_Spain = football[(football.Nationality == 'Spain')].Nationality.value_counts() # Определили общее количество испанцев
s = football[(football.Nationality == 'Spain')].Wage.value_counts(bins=4) #Разбили испанцев на 4 группы по размеру зарплат
Smallest_wage_number = s[s.index[0]] #Определили количество испанцев из группы с самыми малыми зарплатами (обратились к элементу 0 серии s)
display(s)
display(Smallest_wage_number)
Smallest_wage_Percent = (Smallest_wage_number/Total_number_Spain)*100 # Подсчитали процент испанцев с малыми зарплатами от общего числа испанцев.
display(Smallest_wage_Percent)

(620.999, 95750.0]      651
(95750.0, 190500.0]      11
(190500.0, 285250.0]      6
(285250.0, 380000.0]      3
Name: Wage, dtype: int64

651

Spain    97.019374
Name: Nationality, dtype: float64

# 6.6 Задание 2. Укажите количество национальностей (Nationality), к которым относятся футболисты, выступающие за клуб (Club) "Manchester United".

In [56]:
import pandas as pd
football = pd.read_csv('D:\Data Scientist_Skill Factory/data_sf.csv')
s = football[football.Club == 'Manchester United'].Nationality.nunique()#С помощью функции nunique() вывели количевтво уникальных элементов в серии
display(s)

13

# 6.6 Задание 3. С помощью функции unique определите двух футболистов из Бразилии (Nationality = 'Brazil'), выступающих за клуб (Club) 'Juventus'. Перечислите их имена (Name, как в датафрейме) через запятую в алфавитном порядке.

In [60]:
import pandas as pd
football = pd.read_csv('D:\Data Scientist_Skill Factory/data_sf.csv')
s = football[(football.Nationality == 'Brazil')&(football.Club == 'Juventus')].Name.unique()
display(s)

array(['Alex Sandro', 'Douglas Costa'], dtype=object)

# 6.6 Задание 4. Укажите, какой из клубов (Club) насчитывает большее количество футболистов возрастом (Age) старше 35 лет.

In [67]:
import pandas as pd
football = pd.read_csv('D:\Data Scientist_Skill Factory/data_sf.csv')
s = football[football.Age > 35].Club.value_counts()
display(s)

Hokkaido Consadole Sapporo    4
Club Atlético Huracán         4
Club Atlético Tigre           3
Club Atlético Talleres        3
San Martín de San Juan        3
                             ..
UD Las Palmas                 1
AIK                           1
Dundee FC                     1
Valenciennes FC               1
Perth Glory                   1
Name: Club, Length: 212, dtype: int64

# 6.6 Задание 5. С помощью функции value_counts с параметром bins разбейте всех футболистов родом из Аргентины (Nationality = 'Argentina') на 4 равные группы по возрасту. Сколько футболистов в возрасте от 34,75 до 41 года в сборной Аргентины?

In [68]:
import pandas as pd
football = pd.read_csv('D:\Data Scientist_Skill Factory/data_sf.csv')
s = football[football.Nationality == 'Argentina'].Age.value_counts(bins=4)
display(s)

(22.25, 28.5]      200
(15.974, 22.25]    197
(28.5, 34.75]      128
(34.75, 41.0]       49
Name: Age, dtype: int64

# 6.6 Задание 6. Сколько процентов футболистов из Испании (Nationality = 'Spain') имеют возраст (Age) 21 год? Введите с точностью до 2 знаков после запятой без указания знака % (например, 12.35).

In [80]:
import pandas as pd
football = pd.read_csv('D:\Data Scientist_Skill Factory/data_sf.csv')
s = football[football.Nationality == 'Spain'].Age.value_counts(normalize=True)
display(s)

21    0.117735
22    0.095380
20    0.077496
23    0.071535
25    0.064083
27    0.062593
24    0.059613
28    0.053651
26    0.053651
29    0.047690
19    0.047690
18    0.038748
30    0.038748
31    0.032787
32    0.032787
33    0.031297
34    0.022355
17    0.013413
35    0.011923
36    0.010432
37    0.008942
39    0.002981
16    0.002981
38    0.001490
Name: Age, dtype: float64

# 6.7 Задание 1. Отметьте позиции (Position), по которым общая сумма зарплат (Wage) игроков превышает 5 млн евро в год.

In [88]:
import pandas as pd
football = pd.read_csv('D:\Data Scientist_Skill Factory/data_sf.csv')
grouped_football = football.groupby(['Position']).sum()
display(grouped_football)
grouped_football.loc['LS']['Wage']

,Unnamed: 0,Age,Value,Wage,Crossing,Finishing,HeadingAccuracy,ShortPassing,Volleys,Dribbling,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
Position,,,,,,,,,,,,,,,,,,,,,
CAM,4047426,15216,1875705000,5500000,36066,36014,30115,41397,33736,41674,...,35577,38566,25147,25701,24727,6536,6644,6759,6655,6576
CB,9871798,34407,1853715000,7476000,53059,40278,86888,74376,43428,56968,...,55864,75948,86113,90303,86960,14606,14651,14684,14898,14722
CDM,4362394,17271,1146300000,4921000,34679,29548,38651,45501,28742,39869,...,33889,40533,42316,44081,42176,7322,7280,7311,7242,7231
CF,389107,1170,94280000,248000,2627,3148,2620,3081,2839,3349,...,2948,2948,1540,1336,1260,488,475,494,522,525
CM,8666017,24655,1725835000,6194000,55663,50909,53911,70062,48970,64626,...,53456,61422,56303,58933,56643,11096,11091,11080,11198,11103
GK,12004641,42188,2465605000,8784000,23233,19304,23445,43979,19829,22228,...,32217,71723,24590,23112,22998,104190,100570,98548,100341,105337
LAM,12686,168,79475000,366000,426,400,311,423,402,436,...,412,420,197,218,174,71,72,59,58,70
LB,6533552,24958,1431890000,6096000,61171,38486,54216,59167,37552,59681,...,44692,55921,60430,63815,62934,10666,10279,10473,10563,10616
LCB,1837760,11049,1078335000,3989000,17525,12731,27077,23863,13237,18743,...,17071,24631,26787,27840,26993,4342,4422,4268,4384,4277
LCM,1107908,6102,1006115000,3145000,13495,12480,12509,16101,11708,15014,...,12750,14759,13378,13750,12822,2493,2458,2390,2439,2423
LDM,672621,3983,498680000,1516000,8225,7219,8300,10163,6773,9227,...,7820,9285,9076,9425,8786,1562,1557,1577,1625,1593
LF,21760,223,218900000,601000,546,570,457,587,546,628,...,542,593,325,262,260,78,97,76,90,81
LM,4736853,17570,1795375000,5440000,44054,41461,34327,45233,37115,48181,...,40066,42020,29161,27934,26517,7550,7618,7509,7536,7604
LS,536673,3230,707660000,1866000,6147,8277,7737,7321,7456,7968,...,7744,7762,3945,3341,3056,1281,1273,1271,1263,1277
LW,1596722,5615,871950000,2945000,14368,14523,11646,14742,12793,16334,...,13611,14085,8460,8174,7703,2520,2453,2554,2479,2528
LWB,396016,1493,115880000,347000,3712,2428,3196,3589,2349,3592,...,2685,3413,3618,3751,3679,639,678,582,596,640
RAM,13503,132,41725000,59000,337,318,261,351,300,373,...,299,323,181,218,179,60,53,54,45,60
RB,6179705,23646,1183995000,5034000,56785,35949,51671,56231,35433,55869,...,41311,52709,57635,60367,59346,9954,10180,9908,9837,9844
RCB,1883509,11281,1257785000,4711000,17277,13412,27806,24150,13982,18689,...,17629,24994,27528,28468,27361,4417,4327,4464,4379,4418
RCM,1186794,6271,1012225000,3241000,14032,12803,13068,16466,12299,15366,...,12914,15368,13938,14540,13624,2563,2572,2503,2581,2561
RDM,599582,3759,371595000,1557000,7620,6913,8015,9495,6570,8444,...,7255,8804,8682,8947,8454,1439,1466,1533,1507,1507
RF,16306,179,158195000,714000,410,434,313,430,395,449,...,389,432,220,219,204,56,73,60,73,52
RM,5097570,18520,1638270000,5098000,45894,43361,36561,47106,38996,50244,...,41677,43763,30724,29157,27831,8002,8147,8042,8037,8131
RS,535436,3037,415625000,1537000,5576,7700,7185,6796,6736,7306,...,7256,7021,3665,3243,2828,1239,1327,1235,1205,1221
RW,1555981,5492,828490000,3276000,14073,14400,11372,14551,12646,15976,...,13352,13795,8526,7629,7254,2480,2485,2480,2434,2442
RWB,513213,1695,108890000,420000,4186,2865,3515,4148,2693,4185,...,3116,3833,4114,4257,4148,723,752,768,716,692
ST,10809679,36476,3261765000,11873000,65958,97045,92289,83271,82160,91180,...,92651,86425,42224,36649,33538,15692,15763,15961,15904,15793

1866000

# 6.8 Задание 1. Посчитайте среднюю зарплату (Wage) и цену (Value) игроков разных позиций (Position). Представители какой позиции имеют самую высокую среднюю ценность? Какова средняя зарплата футболистов на данной позиции?

In [91]:
import pandas as pd
football = pd.read_csv('D:\Data Scientist_Skill Factory/data_sf.csv')
football.groupby(['Position'])[['Wage','Value']].mean().sort_values(['Value'],ascending=False).head(27)
#В последней строке мы вывели таблицу Position и соответствующие ей среднюю зарплату и среднюю ценность игрока, а так же задали
#сортировку по убыванию средней ценности.

                   Wage         Value
Position
LF         75125.000000  2.736250e+07
RF        119000.000000  2.636583e+07
LAM        61000.000000  1.324583e+07
RAM        11800.000000  8.345000e+06
LS         15421.487603  5.848430e+06
LCM        13497.854077  4.318090e+06
RCM        13504.166667  4.217604e+06
RS         13482.456140  3.645833e+06
LW         12169.421488  3.603099e+06
RW         13822.784810  3.495738e+06
LDM        10243.243243  3.369459e+06
RCB        11270.334928  3.009055e+06
CAM         8688.783570  2.963199e+06
RDM        11282.608696  2.692717e+06
LCB         9753.056235  2.636516e+06
LM          7472.527473  2.466174e+06
ST          7852.513228  2.157252e+06
RM          6655.352480  2.138734e+06
LWB         5783.333333  1.931333e+06
CF          4862.745098  1.848627e+06
CDM         7121.562952  1.658900e+06
CM          5805.060918  1.617465e+06
RWB         6000.000000  1.555571e+06
GK          5352.833638  1.502502e+06
LB          6083.832335  1.429032e+06
CB          5328.581611  1.321251e+06
RB          5310.126582  1.248940e+06

# 6.9 Задание 1. Посчитайте среднюю (mean) и медианную (median) зарплату (Wage) футболистов из разных клубов (Club). В скольких клубах средняя и медианная зарплаты совпадают?
##Подсказка: чтобы в процессе группировки применить к данным одновременно две агрегирующие функции, необходимо указать их как аргументы метода agg:

df.groupby(столбец_для_группировки)[столбцы_для_отображения].agg(['функция_1', 'функция_2'])

In [121]:
import pandas as pd
football = pd.read_csv('D:\Data Scientist_Skill Factory/data_sf.csv')
football.groupby(['Club'])['Wage'].agg(['mean', 'median'])

#s = football[(football.Club.Wage.mean() - football.Club.Wage.median() == 0)].Club.unique()
#display(s)

2

In [156]:
import pandas as pd
football = pd.read_csv('D:\Data Scientist_Skill Factory/data_sf.csv')
s = (football.groupby(['Club']).Wage.mean() - football.groupby(['Club']).Wage.median() == 0)
count = 0
for i in range (0,649):
    if s[s.index[i]] == True: #Этим циклом мы для каждого клуба проверяем равенство средей и медианной зарплаты, 
        count +=1 #и если они равны, тогда счетчик увеличивается на единицу.  
print('Количество клубов с одинаковой средней и медианной зарплатой равняется: ', count)

Количество клубов с одинаковой средней и медианной зарплатой равняется:  52

# 6.9 Задание 2. Продолжаем работать с клубами, в которых средняя зарплата совпадает с медианной. Каков максимальный размер средней зарплаты в этой группе клубов? Как называется клуб, где игроки получают такую зарплату?

In [1]:
import pandas as pd
football = pd.read_csv('D:\Data Scientist_Skill Factory/data_sf.csv')
s = (football.groupby(['Club']).Wage.mean() - football.groupby(['Club']).Wage.median() == 0)
club_ls = [] #Создаем пустой список
wage_ls = [] #Создаем пустой список
for i in range (0,649): #Этим циклом мы для каждого клуба проверяем равенство средей и медианной зарплаты и если они равны, то
    if s[s.index[i]] == True:#в пишем название клуба в список club_ls, а среднюю зарплату в список wage_ls. Индексы i совпадают.
        club_ls.append(s.index[i])
        wage_ls.append(football[football.Club == s.index[i]].Wage.mean())
print(max(wage_ls))
i = 0
while wage_ls[i] != max(wage_ls): #Этим циклом мы перебираем список wage_ls пока не находим максимальный элемент, а найдя его 
    i += 1 # по индексу i находим соответствующий ему элемент из списка club_ls 
print(club_ls[i])

13000.0
Cruzeiro

# 6.10 Задача 1. С помощью функции groupby посчитайте сумму зарплат (Wage) футболистов клуба (Club) "Chelsea".

In [3]:
import pandas as pd
football = pd.read_csv('D:\Data Scientist_Skill Factory/data_sf.csv')
football.groupby([football.Club =='Chelsea'])['Wage'].sum()

Club
False    94919000
True      2035000
Name: Wage, dtype: int64

# 6.10 Задача 2. Определите максимальную зарплату футболиста национальности (Nationality) Аргентина ("Argentina") в возрасте 20 лет.

In [4]:
import pandas as pd
football = pd.read_csv('D:\Data Scientist_Skill Factory/data_sf.csv')
football.groupby([(football.Nationality == 'Argentina')&(football.Age == 20)])['Wage'].max()

False    565000
True      54000
Name: Wage, dtype: int64

# 6.10 Задача 3. Определите максимальную зарплату футболиста национальности (Nationality) Аргентина ("Argentina") в возрасте 30 лет.

In [5]:
import pandas as pd
football = pd.read_csv('D:\Data Scientist_Skill Factory/data_sf.csv')
football.groupby([(football.Nationality == 'Argentina')&(football.Age == 30)])['Wage'].max()

False    565000
True     300000
Name: Wage, dtype: int64

# 6.10 Задача 4. Определите минимальную зарплату футболиста национальности (Nationality) Аргентина ("Argentina") в возрасте 30 лет.

In [6]:
import pandas as pd
football = pd.read_csv('D:\Data Scientist_Skill Factory/data_sf.csv')
football.groupby([(football.Nationality == 'Argentina')&(football.Age == 30)])['Wage'].min()

False    1000
True     1000
Name: Wage, dtype: int64

# 6.10 Задача 4. Определите максимальную силу (Strength) и баланс (Balance) среди игроков клуба (Club) "FC Barcelona" из Аргентины ("Argentina"). Ответ введите через точку с запятой без пробела.

In [13]:
import pandas as pd
football = pd.read_csv('D:\Data Scientist_Skill Factory/data_sf.csv')
football.groupby([(football.Nationality == 'Argentina')&(football.Club == 'FC Barcelona')])['Strength'].max()

False    97
True     59
Name: Strength, dtype: int64

In [12]:
import pandas as pd
football = pd.read_csv('D:\Data Scientist_Skill Factory/data_sf.csv')
football.groupby([(football.Nationality == 'Argentina')&(football.Club == 'FC Barcelona')])['Balance'].max()

False    96
True     95
Name: Balance, dtype: int64

# 6.12 Задача 1. Сводная таблица, показывающая максимальные зарплаты игроков на разных позициях, играющих за разные клубы, была создана с помощью кода:

df2 = df.pivot_table(columns = 'Position', index = 'Club', values = 'Wage', aggfunc = 'max')

# С помощью какого кода можно получить из этой таблицы информацию о максимальной зарплате вратаря (GK), играющего за футбольный клуб "Manchester City"?

In [22]:
import pandas as pd
football = pd.read_csv('D:\Data Scientist_Skill Factory/data_sf.csv')
df2 = football.pivot_table(columns = 'Position', index = 'Club', values = 'Wage', aggfunc = 'max')
df2.loc['Manchester City']['GK']

125000.0

# 6.13 Задание 1. Создайте сводную таблицу, содержащую сведения о количестве игроков, занимающих разные позиции в каждом клубе. Отсутствующие значения замените нулями.

# Каково среднее количество вратарей (GK) в клубе? Ответ округлите до трёх цифр после запятой.

In [40]:
import pandas as pd
football = pd.read_csv('D:\Data Scientist_Skill Factory/data_sf.csv')
df2 = football.pivot_table(columns = 'Club', index = 'Position', aggfunc = 'count', fill_value = 0)
display(df2)

                 Acceleration                                             \
Club      SSV Jahn Regensburg 1. FC Heidenheim 1846 1. FC Kaiserslautern
Position
CAM                         0                     1                    0
CB                          5                     3                    3
CDM                         1                     0                    3
CF                          0                     0                    0
CM                          2                     1                    0
GK                          3                     2                    3
LAM                         0                     0                    0
LB                          2                     2                    2
LCB                         0                     1                    1
LCM                         0                     0                    0
LDM                         1                     0                    0
LF                          0                     0                    0
LM                          2                     2                    2
LS                          0                     0                    1
LW                          0                     0                    1
LWB                         0                     0                    0
RAM                         1                     0                    0
RB                          2                     2                    2
RCB                         1                     1                    0
RCM                         0                     0                    0
RDM                         1                     0                    1
RF                          0                     0                    0
RM                          0                     3                    2
RS                          0                     0                    1
RW                          0                     0                    0
RWB                         0                     0                    0
ST                          3                     2                    1

                                                                       \
Club     1. FC Köln 1. FC Magdeburg 1. FC Nürnberg 1. FC Union Berlin
Position
CAM               0               0              1                  1
CB                1               4              1                  2
CDM               1               0              2                  2
CF                0               1              0                  0
CM                2               0              1                  1
GK                3               3              1                  1
LAM               0               0              0                  0
LB                0               1              1                  2
LCB               0               1              0                  1
LCM               0               1              0                  0
LDM               0               0              0                  0
LF                0               0              0                  0
LM                0               0              0                  0
LS                0               1              0                  0
LW                0               0              0                  0
LWB               1               0              0                  0
RAM               0               0              0                  0
RB                1               0              1                  1
RCB               0               1              0                  0
RCM               0               1              0                  0
RDM               0               0              0                  0
RF                0               0              0                  0
RM                1               3              2                  0
RS                0               1              0                  0
RW                0               2              0                  0
RWB               0               0              0                  0
ST                0               1              3                  0

                                                ...              Wage  \
Club     1. FSV Mainz 05 AC Ajaccio AC Horsens  ... Wycombe Wanderers
Position                                        ...
CAM                    0          3          0  ...                 0
CB                     2          1          3  ...                 3
CDM                    0          0          1  ...                 0
CF                     0          0          0  ...                 0
CM                     1          1          2  ...                 4
GK                     1          1          3  ...                 2
LAM                    0          0          0  ...                 0
LB                     1          3          3  ...                 1
LCB                    0          1          1  ...                 1
LCM                    1          0          1  ...                 1
LDM                    0          1          0  ...                 0
LF                     0          0          0  ...                 0
LM                     0          1          2  ...                 0
LS                     0          0          1  ...                 1
LW                     2          0          0  ...                 3
LWB                    0          0          0  ...                 0
RAM                    0          0          0  ...                 0
RB                     1          1          1  ...                 2
RCB                    0          1          1  ...                 1
RCM                    0          0          1  ...                 1
RDM                    0          1          0  ...                 0
RF                     0          0          0  ...                 0
RM                     0          1          2  ...                 1
RS                     1          0          1  ...                 1
RW                     0          0          0  ...                 1
RWB                    0          0          0  ...                 0
ST                     1          3          2  ...                 1

                                                                          \
Club     Yeni Malatyaspor Yeovil Town Yokohama F. Marinos Zagłębie Lubin
Position
CAM                     2           0                   3              0
CB                      2           3                   4              0
CDM                     3           0                   2              2
CF                      0           0                   0              0
CM                      2           1                   1              1
GK                      4           3                   4              3
LAM                     0           0                   0              0
LB                      1           2                   1              2
LCB                     0           1                   0              1
LCM                     0           1                   1              0
LDM                     1           0                   0              2
LF                      0           0                   0              0
LM                      2           2                   1              2
LS                      0           1                   0              0
LW                      0           0                   1              0
LWB                     0           0                   0              0
RAM                     0           0                   0              0
RB                      2           2                   2              2
RCB                     0           1                   0              1
RCM                     0           1                   1              0
RDM                     0           0                   0              1
RF                      0           0                   0              0
RM                      1           5                   1              4
RS                      0           1                   0              0
RW                      0           0                   1              0
RWB                     0           0                   0              0
ST                      2           4                   3              4

                                                                     \
Club     Zagłębie Sosnowiec Çaykur Rizespor Örebro SK Östersunds FK
Position
CAM                       3               1         0             1
CB                        2               2         4             1
CDM                       2               5         0             0
CF                        0               0         0             1
CM                        0               0         1             3
GK                        3               3         3             3
LAM                       0               0         0             0
LB                        3               2         0             2
LCB                       1               1         1             1
LCM                       0               0         1             1
LDM                       1               1         0             0
LF                        0               0         0             0
LM                        4               1         0             2
LS                        0               0         0             0
LW                        0               0         3             0
LWB                       0               0         2             0
RAM                       0               0         0             0
RB                        1               3         0             1
RCB                       1               0         1             1
RCM                       0               0         1             0
RDM                       1               1         0             0
RF                        0               0         0             0
RM                        2               1         0             1
RS                        0               0         0             0
RW                        0               0         2             1
RWB                       0               0         2             0
ST                        1               1         5             1


Club     Śląsk Wrocław
Position
CAM                  0
CB                   1
CDM                  3
CF                   0
CM                   1
GK                   3
LAM                  0
LB                   2
LCB                  1
LCM                  0
LDM                  1
LF                   0
LM                   2
LS                   1
LW                   0
LWB                  0
RAM                  0
RB                   2
RCB                  1
RCM                  0
RDM                  1
RF                   0
RM                   2
RS                   1
RW                   0
RWB                  0
ST                   2

[27 rows x 26000 columns]

In [42]:
import pandas as pd
football = pd.read_csv('D:\Data Scientist_Skill Factory/data_sf.csv')
df2 = football.pivot_table(columns = 'Club', index = 'Position', aggfunc = 'count', fill_value = 0)
df2.loc['GK'].mean()

2.5246153846153847

In [ ]:
pivot = df.loc[df['Club'].isin(['FC Barcelona','Real Madrid','Juventus','Manchester United'])].pivot_table(values=['Wage'],
index=['Nationality'],
columns=['Club'],
aggfunc='sum',
margins=True,
fill_value=0)
display(pivot)

# 6.13 Задание 2. Используя таблицу, созданную на предыдущем шаге, определите, сколько клубов не содержат данных о центральных полузащитниках. (CM)

## Подсказка: для выполнения этого задания желательно сохранить сводную таблицу в виде отдельного датафрейма и сгруппировать часть данных этого датафрейма с помощью value_counts().

In [4]:
import pandas as pd
football = pd.read_csv('D:\Data Scientist_Skill Factory/data_sf.csv')
df2 = football.pivot_table(columns = 'Club', index = 'Position', aggfunc = 'count', fill_value = 0)
s = df2.loc['CM']['Name']
display(s)
count = 0
for i in range (0, 649):
    if s[s.index[i]] == 0:
        count += 1
print(count)

Club
 SSV Jahn Regensburg     2
1. FC Heidenheim 1846    1
1. FC Kaiserslautern     0
1. FC Köln               2
1. FC Magdeburg          0
                        ..
Zagłębie Sosnowiec       0
Çaykur Rizespor          0
Örebro SK                1
Östersunds FK            3
Śląsk Wrocław            1
Name: CM, Length: 650, dtype: int64

136

# 6.14 Задача 1. С помощью сводной таблицы и функции loc посчитайте, сколько получают ("Wage") русские футболисты ("Russia"), играющие за ФК "AS Monaco".

In [10]:
import pandas as pd
football = pd.read_csv('D:\Data Scientist_Skill Factory/data_sf.csv')
df2 = football.pivot_table(values = 'Wage', columns = 'Club', index = 'Nationality', fill_value = 0)
display(df2)
s = df2.loc['Russia']['AS Monaco'].mean()
print(s)

Club,SSV Jahn Regensburg,1. FC Heidenheim 1846,1. FC Kaiserslautern,1. FC Köln,1. FC Magdeburg,1. FC Nürnberg,1. FC Union Berlin,1. FSV Mainz 05,AC Ajaccio,AC Horsens,...,Wycombe Wanderers,Yeni Malatyaspor,Yeovil Town,Yokohama F. Marinos,Zagłębie Lubin,Zagłębie Sosnowiec,Çaykur Rizespor,Örebro SK,Östersunds FK,Śląsk Wrocław
Nationality,,,,,,,,,,,,,,,,,,,,,
Afghanistan,0.0,0,0,0.0,0.0,0,0.0,0,0,0,...,0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0
Albania,0.0,0,0,0.0,0.0,0,0.0,0,2000,0,...,0,0.0,0.0,0,0,0.0,0.0,1000.0,0.0,0.0
Algeria,0.0,0,0,0.0,0.0,0,0.0,0,0,0,...,0,0.0,1000.0,0,0,0.0,0.0,0.0,0.0,0.0
Andorra,0.0,0,0,0.0,0.0,0,0.0,0,0,0,...,0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0
Angola,0.0,0,0,0.0,0.0,0,0.0,0,0,0,...,0,0.0,0.0,0,0,1000.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Uzbekistan,0.0,0,0,0.0,0.0,0,0.0,0,0,0,...,0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0
Venezuela,0.0,0,0,0.0,0.0,0,0.0,0,0,0,...,0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0
Wales,0.0,0,0,0.0,0.0,0,0.0,0,0,0,...,2000,0.0,2000.0,0,0,0.0,0.0,0.0,0.0,0.0
Zambia,0.0,0,0,0.0,0.0,0,0.0,0,0,0,...,0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0
Zimbabwe,0.0,0,0,0.0,0.0,0,0.0,0,0,0,...,0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0

61000.0

# 6.14 Задача 2. Создайте сводную таблицу, содержащую сведения о средней скорости футболистов (SprintSpeed), занимающих разные позиции (Position) в разных футбольных клубах (Club).

## Основываясь на данных таблицы, отметьте три позиции, представители которых в среднем обладают самой высокой скоростью.

In [47]:
import pandas as pd
football = pd.read_csv('D:\Data Scientist_Skill Factory/data_sf.csv')
df2 = football.pivot_table(values = 'SprintSpeed', columns = 'Club', index = 'Position', fill_value = 0)
df3 = football.loc[football['Position'].isin(['RB','LM','RM','CF','RWM','RS'])].pivot_table(values = 'SprintSpeed', index = 'Position', fill_value = 0).sort_values(['SprintSpeed'],ascending=False).head(6)
display(df2)
display(df3)

Club,SSV Jahn Regensburg,1. FC Heidenheim 1846,1. FC Kaiserslautern,1. FC Köln,1. FC Magdeburg,1. FC Nürnberg,1. FC Union Berlin,1. FSV Mainz 05,AC Ajaccio,AC Horsens,...,Wycombe Wanderers,Yeni Malatyaspor,Yeovil Town,Yokohama F. Marinos,Zagłębie Lubin,Zagłębie Sosnowiec,Çaykur Rizespor,Örebro SK,Östersunds FK,Śląsk Wrocław
Position,,,,,,,,,,,,,,,,,,,,,
CAM,0.000000,68.000000,0.000000,0.0,0.000000,66.000000,61.0,0.0,71.333333,0.000000,...,0.000000,71.500000,0.00,70.333333,0.000000,73.000000,74.000000,0.000000,67.000000,0.000000
CB,46.600000,61.333333,59.000000,60.0,60.000000,55.000000,59.0,71.5,46.000000,53.333333,...,64.666667,62.000000,54.00,45.250000,0.000000,46.500000,58.000000,60.750000,76.000000,62.000000
CDM,82.000000,0.000000,65.666667,32.0,0.000000,59.000000,66.5,0.0,0.000000,56.000000,...,0.000000,65.666667,0.00,61.000000,54.000000,66.000000,62.800000,0.000000,0.000000,66.666667
CF,0.000000,0.000000,0.000000,0.0,64.000000,0.000000,0.0,0.0,0.000000,0.000000,...,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,77.000000,0.000000
CM,61.000000,68.000000,0.000000,68.5,0.000000,53.000000,72.0,69.0,77.000000,62.500000,...,66.500000,64.000000,67.00,67.000000,55.000000,0.000000,0.000000,63.000000,56.333333,72.000000
GK,33.000000,41.000000,42.666667,33.0,39.333333,40.000000,32.0,40.0,46.000000,34.333333,...,44.500000,33.250000,37.00,27.750000,44.666667,39.000000,47.000000,33.666667,32.666667,30.666667
LAM,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,...,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
LB,76.000000,60.000000,68.000000,0.0,69.000000,65.000000,70.5,69.0,67.666667,66.000000,...,75.000000,75.000000,57.00,70.000000,72.000000,60.333333,75.500000,0.000000,74.500000,78.500000
LCB,0.000000,55.000000,45.000000,0.0,60.000000,0.000000,53.0,0.0,52.000000,57.000000,...,45.000000,0.000000,44.00,0.000000,33.000000,61.000000,63.000000,58.000000,53.000000,59.000000
LCM,0.000000,0.000000,0.000000,0.0,66.000000,0.000000,0.0,64.0,0.000000,76.000000,...,65.000000,0.000000,70.00,72.000000,0.000000,0.000000,0.000000,44.000000,62.000000,0.000000
LDM,55.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,64.000000,0.000000,...,0.000000,67.000000,0.00,0.000000,70.000000,74.000000,61.000000,0.000000,0.000000,60.000000
LF,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,...,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
LM,76.000000,69.500000,70.500000,0.0,0.000000,0.000000,0.0,0.0,72.000000,70.500000,...,0.000000,70.000000,83.50,70.000000,66.000000,74.250000,58.000000,0.000000,73.500000,72.000000
LS,0.000000,0.000000,85.000000,0.0,86.000000,0.000000,0.0,0.0,0.000000,77.000000,...,49.000000,0.000000,81.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,55.000000
LW,0.000000,0.000000,80.000000,0.0,0.000000,0.000000,0.0,74.0,0.000000,0.000000,...,80.666667,0.000000,0.00,77.000000,0.000000,0.000000,0.000000,68.333333,0.000000,0.000000
LWB,0.000000,0.000000,0.000000,77.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,...,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,68.000000,0.000000,0.000000
RAM,78.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,...,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
RB,68.500000,80.500000,71.500000,70.0,0.000000,75.000000,86.0,79.0,67.000000,78.000000,...,76.500000,70.500000,69.50,68.500000,69.500000,68.000000,68.666667,0.000000,54.000000,50.500000
RCB,57.000000,59.000000,0.000000,0.0,68.000000,0.000000,0.0,0.0,75.000000,57.000000,...,65.000000,0.000000,59.00,0.000000,50.000000,58.000000,0.000000,62.000000,73.000000,58.000000
RCM,0.000000,0.000000,0.000000,0.0,71.000000,0.000000,0.0,0.0,0.000000,63.000000,...,87.000000,0.000000,76.00,72.000000,0.000000,0.000000,0.000000,66.000000,0.000000,0.000000
RDM,65.000000,0.000000,55.000000,0.0,0.000000,0.000000,0.0,0.0,60.000000,0.000000,...,0.000000,0.000000,0.00,0.000000,61.000000,62.000000,32.000000,0.000000,0.000000,69.000000
RF,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,...,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
RM,0.000000,78.333333,82.500000,77.0,76.000000,83.000000,0.0,0.0,71.000000,61.000000,...,87.000000,87.000000,78.20,61.000000,75.000000,71.000000,85.000000,0.000000,85.000000,68.000000
RS,0.000000,0.000000,69.000000,0.0,53.000000,0.000000,0.0,86.0,0.000000,81.000000,...,69.000000,0.000000,77.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,81.000000
RW,0.000000,0.000000,0.000000,0.0,80.500000,0.000000,0.0,0.0,0.000000,0.000000,...,86.000000,0.000000,0.00,65.000000,0.000000,0.000000,0.000000,77.500000,67.000000,0.000000
RWB,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,...,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,72.000000,0.000000,0.000000
ST,61.666667,69.000000,79.000000,0.0,44.000000,65.666667,0.0,69.0,66.000000,52.500000,...,82.000000,57.500000,74.75,68.666667,65.250000,75.000000,48.000000,72.200000,52.000000,54.000000

          SprintSpeed
Position
RM          74.943864
LM          74.211538
RS          71.991228
RB          71.186709
CF          69.803922

# 6.14 Задача 3. Используя таблицу, созданную на предыдущем шаге, отметьте названия трёх клубов, в которых центральные форварды (ST) обладают наибольшей средней скоростью.

In [48]:
import pandas as pd
football = pd.read_csv('D:\Data Scientist_Skill Factory/data_sf.csv')
df2 = football.pivot_table(values = 'SprintSpeed', columns = 'Club', index = 'Position', fill_value = 0)
df3 = football.loc[football['Position'].isin(['ST'])].pivot_table(values = 'SprintSpeed', index = 'Club', fill_value = 0).sort_values(['SprintSpeed'],ascending=False).head(6)
display(df2)
display(df3)

Club,SSV Jahn Regensburg,1. FC Heidenheim 1846,1. FC Kaiserslautern,1. FC Köln,1. FC Magdeburg,1. FC Nürnberg,1. FC Union Berlin,1. FSV Mainz 05,AC Ajaccio,AC Horsens,...,Wycombe Wanderers,Yeni Malatyaspor,Yeovil Town,Yokohama F. Marinos,Zagłębie Lubin,Zagłębie Sosnowiec,Çaykur Rizespor,Örebro SK,Östersunds FK,Śląsk Wrocław
Position,,,,,,,,,,,,,,,,,,,,,
CAM,0.000000,68.000000,0.000000,0.0,0.000000,66.000000,61.0,0.0,71.333333,0.000000,...,0.000000,71.500000,0.00,70.333333,0.000000,73.000000,74.000000,0.000000,67.000000,0.000000
CB,46.600000,61.333333,59.000000,60.0,60.000000,55.000000,59.0,71.5,46.000000,53.333333,...,64.666667,62.000000,54.00,45.250000,0.000000,46.500000,58.000000,60.750000,76.000000,62.000000
CDM,82.000000,0.000000,65.666667,32.0,0.000000,59.000000,66.5,0.0,0.000000,56.000000,...,0.000000,65.666667,0.00,61.000000,54.000000,66.000000,62.800000,0.000000,0.000000,66.666667
CF,0.000000,0.000000,0.000000,0.0,64.000000,0.000000,0.0,0.0,0.000000,0.000000,...,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,77.000000,0.000000
CM,61.000000,68.000000,0.000000,68.5,0.000000,53.000000,72.0,69.0,77.000000,62.500000,...,66.500000,64.000000,67.00,67.000000,55.000000,0.000000,0.000000,63.000000,56.333333,72.000000
GK,33.000000,41.000000,42.666667,33.0,39.333333,40.000000,32.0,40.0,46.000000,34.333333,...,44.500000,33.250000,37.00,27.750000,44.666667,39.000000,47.000000,33.666667,32.666667,30.666667
LAM,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,...,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
LB,76.000000,60.000000,68.000000,0.0,69.000000,65.000000,70.5,69.0,67.666667,66.000000,...,75.000000,75.000000,57.00,70.000000,72.000000,60.333333,75.500000,0.000000,74.500000,78.500000
LCB,0.000000,55.000000,45.000000,0.0,60.000000,0.000000,53.0,0.0,52.000000,57.000000,...,45.000000,0.000000,44.00,0.000000,33.000000,61.000000,63.000000,58.000000,53.000000,59.000000
LCM,0.000000,0.000000,0.000000,0.0,66.000000,0.000000,0.0,64.0,0.000000,76.000000,...,65.000000,0.000000,70.00,72.000000,0.000000,0.000000,0.000000,44.000000,62.000000,0.000000
LDM,55.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,64.000000,0.000000,...,0.000000,67.000000,0.00,0.000000,70.000000,74.000000,61.000000,0.000000,0.000000,60.000000
LF,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,...,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
LM,76.000000,69.500000,70.500000,0.0,0.000000,0.000000,0.0,0.0,72.000000,70.500000,...,0.000000,70.000000,83.50,70.000000,66.000000,74.250000,58.000000,0.000000,73.500000,72.000000
LS,0.000000,0.000000,85.000000,0.0,86.000000,0.000000,0.0,0.0,0.000000,77.000000,...,49.000000,0.000000,81.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,55.000000
LW,0.000000,0.000000,80.000000,0.0,0.000000,0.000000,0.0,74.0,0.000000,0.000000,...,80.666667,0.000000,0.00,77.000000,0.000000,0.000000,0.000000,68.333333,0.000000,0.000000
LWB,0.000000,0.000000,0.000000,77.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,...,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,68.000000,0.000000,0.000000
RAM,78.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,...,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
RB,68.500000,80.500000,71.500000,70.0,0.000000,75.000000,86.0,79.0,67.000000,78.000000,...,76.500000,70.500000,69.50,68.500000,69.500000,68.000000,68.666667,0.000000,54.000000,50.500000
RCB,57.000000,59.000000,0.000000,0.0,68.000000,0.000000,0.0,0.0,75.000000,57.000000,...,65.000000,0.000000,59.00,0.000000,50.000000,58.000000,0.000000,62.000000,73.000000,58.000000
RCM,0.000000,0.000000,0.000000,0.0,71.000000,0.000000,0.0,0.0,0.000000,63.000000,...,87.000000,0.000000,76.00,72.000000,0.000000,0.000000,0.000000,66.000000,0.000000,0.000000
RDM,65.000000,0.000000,55.000000,0.0,0.000000,0.000000,0.0,0.0,60.000000,0.000000,...,0.000000,0.000000,0.00,0.000000,61.000000,62.000000,32.000000,0.000000,0.000000,69.000000
RF,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,...,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
RM,0.000000,78.333333,82.500000,77.0,76.000000,83.000000,0.0,0.0,71.000000,61.000000,...,87.000000,87.000000,78.20,61.000000,75.000000,71.000000,85.000000,0.000000,85.000000,68.000000
RS,0.000000,0.000000,69.000000,0.0,53.000000,0.000000,0.0,86.0,0.000000,81.000000,...,69.000000,0.000000,77.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,81.000000
RW,0.000000,0.000000,0.000000,0.0,80.500000,0.000000,0.0,0.0,0.000000,0.000000,...,86.000000,0.000000,0.00,65.000000,0.000000,0.000000,0.000000,77.500000,67.000000,0.000000
RWB,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,...,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,72.000000,0.000000,0.000000
ST,61.666667,69.000000,79.000000,0.0,44.000000,65.666667,0.0,69.0,66.000000,52.500000,...,82.000000,57.500000,74.75,68.666667,65.250000,75.000000,48.000000,72.200000,52.000000,54.000000

                   SprintSpeed
Club
Vitória              91.000000
Sydney FC            88.000000
CD Lugo              87.000000
Brøndby IF           84.666667
Leicester City       84.500000
Manchester United    84.000000